# Generated by Django 5.2.17 on 2026-09-26 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("mecl_ref", models.CharField(max_length=24, unique=True)),
                (
                    "agreement_no",
                    models.CharField(
                        blank=True,
                        help_text="Amazon agreement number (rule R8: unique)",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PA", "Personal audio"),
                            ("DI", "Digital imaging"),
                            ("TV", "Television"),
                            ("HAV", "Home audio & video"),
                            ("Bundle", "Bundles"),
                        ],
                        max_length=8,
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("dn_due", models.DateTimeField()),
                ("owner_name", models.CharField(max_length=120)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("rejected", "Rejected by Amazon"),
                            ("approved", "Approved"),
                            ("dn_validated", "DN validated"),
                            ("claimed", "Claimed"),
                            ("cn_shortfall", "CN shortfall"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=14,
                    ),
                ),
            ],
            options={
                "ordering": ["-start"],
            },
        ),
        migrations.CreateModel(
            name="PromoLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "support_h",
                    models.BigIntegerField(help_text="Support per unit, halalas"),
                ),
                ("expected_units", models.IntegerField()),
                (
                    "sold_units",
                    models.IntegerField(
                        blank=True, help_text="From the Amazon sales report", null=True
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.sku"
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
