# Generated by Django 5.2.17 on 2026-10-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promo_type',
            field=models.CharField(choices=[('price_discount', 'Price discount'), ('deal', 'Deal (Lightning / Best Deal)'), ('coupon', 'Coupon'), ('prime_day', 'Prime Day / event'), ('price_protection', 'Price protection'), ('other', 'Other')], default='price_discount', max_length=20),
        ),
    ]
