# Generated by Django 5.2.17 on 2026-10-01 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='dn_instalments',
            field=models.BooleanField(default=False, help_text='Amazon bills this promotion in parts (e.g. monthly debit notes)'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('PA', 'Personal audio'), ('DI', 'Digital imaging'), ('TV', 'Television'), ('HAV', 'Home audio & video'), ('Bundle', 'Bundles')], max_length=8)),
                ('year', models.PositiveIntegerField()),
                ('quarter', models.PositiveSmallIntegerField()),
                ('amount_h', models.BigIntegerField()),
            ],
            options={
                'ordering': ['year', 'quarter', 'category'],
                'constraints': [models.UniqueConstraint(fields=('category', 'year', 'quarter'), name='uniq_budget')],
            },
        ),
        migrations.CreateModel(
            name='PromoAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('no', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('changes', models.JSONField(default=list)),
                ('by_name', models.CharField(blank=True, max_length=120)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='promotions.promotion')),
            ],
            options={
                'ordering': ['no'],
            },
        ),
        migrations.CreateModel(
            name='PromoFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(max_length=80)),
                ('amount_h', models.BigIntegerField()),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='promotions.promotion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
