# Generated by Django 5.2.17 on 2026-10-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='brand_ref',
            field=models.CharField(blank=True, help_text='Second reference, e.g. 0125CAV-PAMKT158', max_length=40),
        ),
        migrations.AddField(
            model_name='promotion',
            name='sf_ref',
            field=models.CharField(blank=True, help_text='MECL reference from Salesforce, e.g. PRO-004559', max_length=30),
        ),
        migrations.AddField(
            model_name='promotion',
            name='subcat',
            field=models.CharField(blank=True, help_text='Sub-category code, e.g. GPA', max_length=12),
        ),
    ]
