# Generated by Django 5.2.17 on 2026-09-26 19:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("orders", "0001_initial"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("case_no", models.CharField(max_length=20, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("shortage", "Shortage"),
                            ("price", "Price"),
                            ("promo", "Promo deduction"),
                            ("damage", "Damage"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        help_text="Payment or debit note number", max_length=40
                    ),
                ),
                ("amount_h", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("submitted", "With Amazon"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("due", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.TextField(blank=True)),
                (
                    "po",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.purchaseorder",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("filename", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="evidence/%Y/%m/"
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="payments.dispute",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("payment_no", models.CharField(max_length=30, unique=True)),
                ("remit_date", models.DateTimeField()),
                (
                    "invoice_ref",
                    models.CharField(
                        help_text="Invoice number exactly as Amazon sent it",
                        max_length=40,
                    ),
                ),
                ("paid_h", models.BigIntegerField()),
                ("deduction_h", models.BigIntegerField(default=0)),
                ("reason", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("imported", "Imported"),
                            ("matched", "Matched"),
                            ("short", "Short-paid"),
                            ("unmatched", "To match"),
                            ("accepted", "Deduction accepted"),
                            ("disputed", "Disputed"),
                            ("recovered", "Recovered"),
                        ],
                        db_index=True,
                        default="imported",
                        max_length=10,
                    ),
                ),
                ("hint", models.CharField(blank=True, max_length=40)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="billing.invoice",
                    ),
                ),
                (
                    "po",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="orders.purchaseorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-remit_date"],
            },
        ),
    ]
