# Generated by Django 5.2.17 on 2026-10-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='amazon_case_id',
            field=models.CharField(blank=True, help_text='Case ID from Vendor Central', max_length=40),
        ),
        migrations.AddField(
            model_name='dispute',
            name='recovered_h',
            field=models.BigIntegerField(blank=True, help_text='Amount Amazon gave back (may be part of the claim)', null=True),
        ),
    ]
