# Generated by Django 5.2.17 on 2026-10-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_dispute_case_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='recovered_in',
            field=models.CharField(blank=True, help_text='The later payment that brought the money back', max_length=30),
        ),
        migrations.AddField(
            model_name='dispute',
            name='subtype',
            field=models.CharField(blank=True, choices=[('asn_accuracy', 'ASN accuracy'), ('asn_ontime', 'ASN on-time'), ('labels', 'Carton / pallet labels'), ('po_ontime', 'PO on-time accuracy'), ('prep', 'Prep / packaging'), ('overweight', 'Overweight / oversize carton'), ('appointment', 'Missed or late appointment'), ('other', 'Other chargeback')], help_text='Chargeback type', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='type',
            field=models.CharField(choices=[('shortage', 'Shortage'), ('price', 'Price'), ('promo', 'Promo deduction'), ('damage', 'Damage'), ('chargeback', 'Chargeback'), ('returns', 'Returns (RTV)'), ('coop', 'Co-op / advertising'), ('other', 'Other')], max_length=10),
        ),
    ]
