# Generated by Django 5.2.17 on 2026-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_dispute_categories_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vendor_code',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
    ]
