# Generated by Django 5.2.17 on 2026-10-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='When it was won or lost', null=True),
        ),
    ]
