# Generated by Django 5.2.17 on 2026-10-01 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoiceline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amazon_note',
            field=models.CharField(blank=True, help_text="Amazon's reason for a hold or rejection", max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amazon_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('on_hold', 'On hold at Amazon'), ('rejected', 'Rejected by Amazon')], db_index=True, default='submitted', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='revision',
            field=models.PositiveIntegerField(default=0, help_text='Times the invoice was corrected and sent again'),
        ),
        migrations.CreateModel(
            name='CreditMemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('memo_no', models.CharField(max_length=30, unique=True)),
                ('amount_h', models.BigIntegerField(help_text='Including VAT')),
                ('reason', models.CharField(max_length=200)),
                ('by_name', models.CharField(blank=True, max_length=120)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_memos', to='billing.invoice')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
