# Generated by Django 5.2.17 on 2026-10-01 13:05

import django.db.models.deletion
from django.db import migrations, models


def link(apps, schema_editor):
    """Existing data: one shipment per PO, so each invoice / billing belongs to the PO's shipment."""
    Shipment = apps.get_model("fulfilment", "Shipment")
    for M in (apps.get_model("billing", "Invoice"), apps.get_model("billing", "SapBilling")):
        for x in M.objects.filter(shipment__isnull=True):
            x.shipment = Shipment.objects.filter(po_id=x.po_id).first()
            x.save(update_fields=["shipment"])
    for sh in Shipment.objects.filter(delivered_at__isnull=True):
        if sh.po.delivered_at:
            sh.delivered_at = sh.po.delivered_at
            sh.save(update_fields=["delivered_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_status_credit_memos'),
        ('fulfilment', '0004_split_shipments'),
        ('orders', '0005_backorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='seq',
            field=models.PositiveIntegerField(default=1, help_text='Invoice per shipment: 1st, 2nd …'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='fulfilment.shipment'),
        ),
        migrations.AddField(
            model_name='sapbilling',
            name='seq',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sapbilling',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='fulfilment.shipment'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orders.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='sapbilling',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_billings', to='orders.purchaseorder'),
        ),
        migrations.RunPython(link, migrations.RunPython.noop),
    ]
