# Generated by Django 5.2.17 on 2026-09-26 19:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(db_index=True, max_length=30)),
                ("entity_id", models.CharField(db_index=True, max_length=64)),
                ("action", models.CharField(blank=True, max_length=60)),
                ("text", models.TextField()),
                ("actor_name", models.CharField(max_length=120)),
                ("system", models.BooleanField(default=False)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("request_id", models.CharField(blank=True, max_length=64)),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40, unique=True)),
                ("value", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("kind", models.CharField(max_length=30)),
                ("filename", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("entity", models.CharField(max_length=30)),
                ("entity_id", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("entity", models.CharField(max_length=30)),
                ("entity_id", models.CharField(max_length=64)),
                ("text", models.TextField()),
                ("author_name", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("ok", "OK"),
                            ("warn", "Warning"),
                            ("bad", "Problem"),
                        ],
                        default="info",
                        max_length=8,
                    ),
                ),
                ("link_type", models.CharField(blank=True, max_length=20)),
                ("link_id", models.CharField(blank=True, max_length=64)),
                ("link_tab", models.CharField(blank=True, max_length=20)),
                ("read", models.BooleanField(default=False)),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-id"],
            },
        ),
    ]
