# Generated by Django 5.2.17 on 2026-10-01 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_audit_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('entity', models.CharField(max_length=30)),
                ('entity_id', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('pod', 'Proof of delivery'), ('evidence', 'Evidence'), ('other', 'Other')], default='other', max_length=10)),
                ('filename', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='docs/%Y/%m/')),
                ('uploaded_by_name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='core_attach_entity_6a1f58_idx')],
            },
        ),
    ]
