# Generated by Django 5.2.17 on 2026-10-01 12:21

import uuid
from datetime import date

from django.db import migrations, models

FIXED = [(2, 22, "Founding Day"), (9, 23, "Saudi National Day")]


def add_fixed_holidays(apps, schema_editor):
    """The fixed-date national holidays; Eid dates follow the Hijri calendar and are added each year in Settings."""
    Holiday = apps.get_model("core", "Holiday")
    for y in (2026, 2027):
        for mth, d, name in FIXED:
            Holiday.objects.get_or_create(day=date(y, mth, d), defaults={"name": name})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('day', models.DateField(unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.RunPython(add_fixed_holidays, migrations.RunPython.noop),
    ]
