# Generated by Django 5.2.17 on 2026-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alert_scope',
            field=models.CharField(choices=[('mine', 'My work and mentions'), ('all', 'Everything')], default='mine', max_length=8),
        ),
    ]
