# Generated by Django 5.2.17 on 2026-09-26 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("debitnotes", "0001_initial"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("claim_no", models.CharField(max_length=20, unique=True)),
                ("amount_h", models.BigIntegerField()),
                ("sent_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Waiting for CN"),
                            ("closed", "Closed"),
                            ("shortfall", "CN shortfall"),
                            ("written_off", "Written off"),
                        ],
                        db_index=True,
                        default="sent",
                        max_length=12,
                    ),
                ),
                ("cn_no", models.CharField(blank=True, max_length=30)),
                ("cn_h", models.BigIntegerField(blank=True, null=True)),
                ("cn_date", models.DateTimeField(blank=True, null=True)),
                (
                    "debit_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="debitnotes.debitnote",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
