# Generated by Django 5.2.17 on 2026-10-01 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill(apps, schema_editor):
    Claim, CreditNote = apps.get_model("claims", "Claim"), apps.get_model("claims", "CreditNote")
    for c in Claim.objects.exclude(cn_no="").filter(cn_h__isnull=False):
        CreditNote.objects.get_or_create(claim=c, cn_no=c.cn_no, defaults=dict(amount_h=c.cn_h, cn_date=c.cn_date or c.updated_at))


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('cn_no', models.CharField(max_length=30)),
                ('amount_h', models.BigIntegerField()),
                ('cn_date', models.DateTimeField()),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='claims.claim')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('claim', 'cn_no'), name='uniq_cn_per_claim')],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
