# Generated by Django 5.2.17 on 2026-10-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_credit_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='batch_no',
            field=models.CharField(blank=True, db_index=True, help_text='Claims sent together in one batch', max_length=20),
        ),
    ]
