# Generated by Django 5.2.17 on 2026-10-01 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_case_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('rtv_no', models.CharField(help_text="Amazon's return / authorisation number", max_length=30, unique=True)),
                ('vendor_code', models.CharField(blank=True, max_length=12)),
                ('reason', models.CharField(choices=[('defective', 'Defective / customer return'), ('overstock', 'Overstock (returnable under the agreement)'), ('recall', 'Recall'), ('wrong_item', 'Wrong item received'), ('other', 'Other')], default='defective', max_length=12)),
                ('status', models.CharField(choices=[('requested', 'To authorise'), ('refused', 'Refused'), ('authorised', 'Authorised, on its way'), ('received', 'Received'), ('credited', 'Credited'), ('disputed', 'Disputed')], db_index=True, default='requested', max_length=12)),
                ('requested_at', models.DateTimeField()),
                ('authorised_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('payment_no', models.CharField(blank=True, help_text='The payment whose deduction covers this return', max_length=30)),
                ('dispute_no', models.CharField(blank=True, max_length=20)),
                ('fc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.fulfilmentcentre')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('qty', models.IntegerField()),
                ('unit_cost_h', models.BigIntegerField()),
                ('qty_received', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, choices=[('good', 'Good, resaleable'), ('damaged', 'Damaged'), ('missing', 'Missing')], max_length=8)),
                ('rtv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.returnauth')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.sku')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
