# Generated by Django 5.2.17 on 2026-09-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sapdeliveryline',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='shipmentline',
            options={'ordering': ['created_at']},
        ),
    ]
