# Generated by Django 5.2.17 on 2026-10-01 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_case_pack'),
        ('fulfilment', '0002_alter_sapdeliveryline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='freight',
            field=models.CharField(choices=[('prepaid', 'ME books the delivery (Carrier Central)'), ('collect', 'Amazon collects (routing request)')], default='prepaid', max_length=8),
        ),
        migrations.AddField(
            model_name='shipment',
            name='reschedules',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='slot_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='slot_outcome',
            field=models.CharField(blank=True, help_text='missed / refused: the last appointment failed', max_length=10),
        ),
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('seq', models.PositiveIntegerField()),
                ('sscc', models.CharField(max_length=18, unique=True)),
                ('qty', models.IntegerField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carton_list', to='fulfilment.shipment')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.sku')),
            ],
            options={
                'ordering': ['shipment', 'seq'],
            },
        ),
    ]
