# Generated by Django 5.2.17 on 2026-10-01 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0003_cartons_freight_slots'),
        ('orders', '0005_backorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapdelivery',
            name='seq',
            field=models.PositiveIntegerField(default=1, help_text='1st, 2nd … delivery for the PO'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='seq',
            field=models.PositiveIntegerField(default=1, help_text='1st, 2nd … shipment for the PO'),
        ),
        migrations.AlterField(
            model_name='sapdelivery',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_deliveries', to='orders.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.purchaseorder'),
        ),
    ]
