# Generated by Django 5.2.17 on 2026-10-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0004_split_shipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapdelivery',
            name='sales_order',
            field=models.CharField(blank=True, help_text='Sales order of this booking portion', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sales_order',
            field=models.CharField(blank=True, help_text='Sales order of this booking portion', max_length=20),
        ),
    ]
