# Generated by Django 5.2.17 on 2026-09-26 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebitNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("dn_no", models.CharField(max_length=30, unique=True)),
                (
                    "agreement_no",
                    models.CharField(
                        db_index=True,
                        help_text="As received from Amazon",
                        max_length=20,
                    ),
                ),
                ("dn_date", models.DateTimeField()),
                ("validated", models.BooleanField(default=False)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_h", models.BigIntegerField(default=0)),
                ("disputed_h", models.BigIntegerField(default=0)),
                ("override_reason", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-dn_date"],
            },
        ),
        migrations.CreateModel(
            name="DnLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("units", models.IntegerField()),
                ("rate_h", models.BigIntegerField()),
                (
                    "dn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="debitnotes.debitnote",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.sku"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
