# Generated by Django 5.2.17 on 2026-10-01 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_case_pack'),
        ('debitnotes', '0002_alter_dnline_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnline',
            name='label',
            field=models.CharField(blank=True, help_text='Fixed-fee lines: what the fee is', max_length=80),
        ),
        migrations.AlterField(
            model_name='dnline',
            name='sku',
            field=models.ForeignKey(blank=True, help_text='Empty for a fixed-fee line', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.sku'),
        ),
    ]
