# Generated by Django 5.2.17 on 2026-09-26 19:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("key", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=60)),
                ("short", models.CharField(max_length=4)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("off", "Off"),
                            ("file", "File upload"),
                            ("manual", "Manual entry"),
                            ("api", "API"),
                            ("edi", "EDI"),
                            ("odata", "OData"),
                            ("idoc", "IDoc"),
                            ("bapi", "BAPI / RFC"),
                            ("smtp", "SMTP relay"),
                            ("m365", "Microsoft 365"),
                            ("entra", "Microsoft Entra ID"),
                            ("saml", "SAML 2.0"),
                        ],
                        default="off",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("records_today", models.IntegerField(default=0)),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, help_text="Non-secret settings only"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("kind", models.CharField(max_length=30)),
                ("ok", models.BooleanField(default=True)),
                ("message", models.CharField(max_length=300)),
                ("records_in", models.IntegerField(default=0)),
                ("records_out", models.IntegerField(default=0)),
                (
                    "finished_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="integrations.connector",
                    ),
                ),
            ],
            options={
                "ordering": ["-finished_at"],
            },
        ),
    ]
