# Generated by Django 5.2.17 on 2026-09-30 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('auto_apply', models.BooleanField(default=False, help_text='Apply a payment → invoice match without review')),
                ('auto_threshold', models.PositiveSmallIntegerField(default=95)),
                ('show_threshold', models.PositiveSmallIntegerField(default=50)),
                ('ai_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('pay_inv', 'Payment → invoice'), ('pay_dn', 'Short payment → debit note'), ('dn_promo', 'Debit note → promotion'), ('deduction', 'Deduction reason')], max_length=10)),
                ('source', models.CharField(help_text='Payment or debit note number', max_length=40)),
                ('targets', models.JSONField(default=list, help_text='Invoice numbers, DN number, MECL ref, or a deduction type')),
                ('label', models.CharField(max_length=200)),
                ('score', models.PositiveSmallIntegerField()),
                ('reasons', models.JSONField(default=list)),
                ('method', models.CharField(default='rules', help_text='rules, or ai when Claude picked it', max_length=5)),
                ('ai_model', models.CharField(blank=True, max_length=60)),
                ('ai_rationale', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='e.g. recommended action and draft note for a deduction')),
                ('status', models.CharField(choices=[('pending', 'To review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('auto', 'Applied automatically'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=10)),
                ('decided_by_name', models.CharField(blank=True, max_length=120)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'created_at'],
                'indexes': [models.Index(fields=['kind', 'source', 'status'], name='matching_ma_kind_fc091f_idx')],
            },
        ),
    ]
