# Generated by Django 5.2.17 on 2026-10-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsettings',
            name='ai_provider',
            field=models.CharField(choices=[('off', 'Not connected'), ('anthropic', 'Anthropic API'), ('bedrock', 'Amazon Bedrock')], default='off', max_length=10),
        ),
        migrations.AddField(
            model_name='matchsettings',
            name='api_key_enc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchsettings',
            name='api_key_hint',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='matchsettings',
            name='api_key_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchsettings',
            name='api_key_set_by',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
