# Generated by Django 5.2.17 on 2026-10-01 05:45

from django.db import migrations, models


def keys_saved_earlier_are_anthropic(apps, schema_editor):
    """Before OpenAI was added, the only saved key was a Claude (Anthropic API) key."""
    apps.get_model("matching", "MatchSettings").objects.exclude(api_key_enc="").update(api_key_for="anthropic")


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_ai_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsettings',
            name='ai_model',
            field=models.CharField(blank=True, help_text='Model name; required for OpenAI, optional otherwise', max_length=80),
        ),
        migrations.AddField(
            model_name='matchsettings',
            name='api_key_for',
            field=models.CharField(blank=True, help_text='Provider the saved key belongs to', max_length=10),
        ),
        migrations.AlterField(
            model_name='matchsettings',
            name='ai_provider',
            field=models.CharField(choices=[('off', 'Not connected'), ('anthropic', 'Anthropic API'), ('openai', 'OpenAI'), ('bedrock', 'Amazon Bedrock')], default='off', max_length=10),
        ),
        migrations.RunPython(keys_saved_earlier_are_anthropic, migrations.RunPython.noop),
    ]
