# Generated by Django 5.2.17 on 2026-09-26 19:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FulfilmentCentre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("city", models.CharField(max_length=60)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Sku",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("sku_code", models.CharField(max_length=20, unique=True)),
                ("model_no", models.CharField(max_length=40, unique=True)),
                ("asin", models.CharField(max_length=12, unique=True)),
                ("ean", models.CharField(blank=True, max_length=20)),
                ("description", models.CharField(blank=True, max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PA", "Personal audio"),
                            ("DI", "Digital imaging"),
                            ("TV", "Television"),
                            ("HAV", "Home audio & video"),
                            ("Bundle", "Bundles"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "cost_h",
                    models.BigIntegerField(
                        default=0, help_text="Current agreed Amazon cost, halalas"
                    ),
                ),
                ("free_stock", models.IntegerField(default=0)),
                (
                    "stock_as_of",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sku_code"],
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("cost_h", models.BigIntegerField()),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="catalog.sku",
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from"],
            },
        ),
    ]
