# Generated by Django 5.2.17 on 2026-10-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='case_pack',
            field=models.PositiveIntegerField(default=1, help_text='Units per case; PO quantities should be whole cases'),
        ),
    ]
