# Generated by Django 5.2.17 on 2026-10-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_case_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='lifecycle',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('phase_out', 'Phase-out'), ('eol', 'EOL')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='sku',
            name='rrp_h',
            field=models.BigIntegerField(blank=True, help_text='Recommended retail price incl. VAT, halalas', null=True),
        ),
        migrations.CreateModel(
            name='AmazonStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(db_index=True)),
                ('units', models.IntegerField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_stock', to='catalog.sku')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sku', 'as_of'), name='uniq_amazon_stock')],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('sellout_units', models.IntegerField()),
                ('sellin_units', models.IntegerField(blank=True, help_text='Empty: the tracker estimates it', null=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='catalog.sku')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sku', 'month'), name='uniq_forecast_month')],
            },
        ),
        migrations.CreateModel(
            name='SellOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('units', models.IntegerField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellout', to='catalog.sku')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sku', 'day'), name='uniq_sellout_day')],
            },
        ),
    ]
