# Generated by Django 5.2.17 on 2026-09-26 19:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RuleConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("rule_id", models.CharField(max_length=4, unique=True)),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=160)),
                ("enabled", models.BooleanField(default=True)),
                ("params", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(max_length=20)),
                ("entity_id", models.CharField(max_length=64)),
                ("rule_id", models.CharField(max_length=4)),
                ("subject", models.CharField(blank=True, max_length=80)),
                ("passed", models.BooleanField(null=True)),
                ("expected", models.CharField(blank=True, max_length=60)),
                ("actual", models.CharField(blank=True, max_length=60)),
                ("gap", models.CharField(blank=True, max_length=60)),
                ("config_version", models.PositiveIntegerField(default=1)),
                ("run_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity", "entity_id"],
                        name="rules_check_entity_a44f11_idx",
                    )
                ],
            },
        ),
    ]
