# Generated by Django 5.2.17 on 2026-09-26 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("po_no", models.CharField(max_length=20, unique=True)),
                ("order_date", models.DateTimeField()),
                ("confirm_by", models.DateTimeField()),
                ("window_start", models.DateTimeField(blank=True, null=True)),
                ("window_end", models.DateTimeField(blank=True, null=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "To confirm"),
                            ("confirmed", "Confirmed"),
                            ("booked", "Booked in SAP"),
                            ("released", "Released"),
                            ("asn", "ASN sent"),
                            ("slot", "Slot booked"),
                            ("delivered", "Delivered"),
                            ("invoiced", "Invoiced"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("booked_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("sap_order_no", models.CharField(blank=True, max_length=20)),
                ("sf_order_id", models.CharField(blank=True, max_length=20)),
                (
                    "fc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos",
                        to="catalog.fulfilmentcentre",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="PoLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("position", models.PositiveIntegerField(default=0)),
                ("asin", models.CharField(max_length=12)),
                ("qty_ordered", models.IntegerField()),
                ("cost_h", models.BigIntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("accept", "Accept"),
                            ("partial", "Partial"),
                            ("reject", "Reject"),
                        ],
                        default="accept",
                        max_length=8,
                    ),
                ),
                ("qty_confirmed", models.IntegerField(default=0)),
                ("reason", models.CharField(blank=True, max_length=120)),
                (
                    "touched",
                    models.BooleanField(
                        default=False, help_text="User changed the suggested decision"
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.sku"
                    ),
                ),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="orders.purchaseorder",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
