# Generated by Django 5.2.17 on 2026-10-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='credit_hold',
            field=models.CharField(blank=True, help_text='Why credit control is holding the order', max_length=200),
        ),
    ]
