# Generated by Django 5.2.17 on 2026-10-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_credit_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='stage',
            field=models.CharField(choices=[('new', 'To confirm'), ('confirmed', 'Confirmed'), ('booked', 'Booked in SAP'), ('released', 'Released'), ('asn', 'ASN sent'), ('slot', 'Slot booked'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled by Amazon')], db_index=True, default='new', max_length=12),
        ),
    ]
