# Generated by Django 5.2.17 on 2026-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cancelled_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_code',
            field=models.CharField(blank=True, db_index=True, help_text='Amazon vendor code the PO was sent to', max_length=12),
        ),
    ]
