# Generated by Django 5.2.17 on 2026-10-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='poline',
            name='backorder_eta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poline',
            name='qty_backorder',
            field=models.IntegerField(default=0, help_text='Units acknowledged as backordered, shipped later'),
        ),
        migrations.AlterField(
            model_name='poline',
            name='decision',
            field=models.CharField(choices=[('accept', 'Accept'), ('partial', 'Partial'), ('backorder', 'Backorder rest'), ('reject', 'Reject')], default='accept', max_length=10),
        ),
        migrations.AlterField(
            model_name='poline',
            name='qty_confirmed',
            field=models.IntegerField(default=0, help_text='Units confirmed to ship now'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='stage',
            field=models.CharField(choices=[('new', 'To confirm'), ('confirmed', 'Confirmed'), ('booked', 'Booked in SAP'), ('released', 'Released'), ('asn', 'ASN sent'), ('slot', 'Slot booked'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('backorder', 'Backorder open'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled by Amazon')], db_index=True, default='new', max_length=12),
        ),
    ]
