# Generated by Django 5.2.17 on 2026-10-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_backorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='rfpo',
            field=models.CharField(blank=True, help_text="ME's release / booking reference (RFPO)", max_length=30),
        ),
    ]
