# Generated by Django 5.2.17 on 2026-09-26 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_type", models.CharField(max_length=4)),
                ("header_signature", models.CharField(max_length=64)),
                ("mapping", models.JSONField()),
            ],
            options={
                "unique_together": {("upload_type", "header_signature")},
            },
        ),
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("upload_type", models.CharField(max_length=4)),
                ("filename", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="uploads/%Y/%m/"),
                ),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("headers", models.JSONField(default=list)),
                ("raw_rows", models.JSONField(default=list)),
                ("mapping", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("mapping", "Mapping"),
                            ("preview", "Preview"),
                            ("committed", "Imported"),
                            ("failed", "Failed"),
                        ],
                        default="mapping",
                        max_length=10,
                    ),
                ),
                ("rows_total", models.IntegerField(default=0)),
                ("created_count", models.IntegerField(default=0)),
                ("updated_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("warning_count", models.IntegerField(default=0)),
                ("summary", models.JSONField(default=list)),
                ("uploaded_by_name", models.CharField(blank=True, max_length=120)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_no", models.IntegerField()),
                ("data", models.JSONField()),
                ("errors", models.JSONField(default=list)),
                ("warnings", models.JSONField(default=list)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="uploads.uploadbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["row_no"],
            },
        ),
    ]
